### PR TITLE
Managed identity

### PR DESCRIPTION
**Pull request by dan-corneanu**
Trying to implement authorisation with Microsoft Entra ID and managed identities.
Some relevant documentation:
* [Authorize with Microsoft Entra ID](https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-azure-active-directory)
* [Create a user delegation SAS](https://learn.microsoft.com/en-us/rest/api/storageservices/create-user-delegation-sas)

### CODE REVIEW

**Comment by dan-corneanu** [comment]
@JoeDupuis Could you please have a look at this PR and let me know what you think?

When I run the code on a VM with a managed identity, I can upload and download files without specifying a `storage_access_key` in the configuration. However, I have issues with generating valid user delegation SAS links. 

E.g. with this link
https://app718c0c02f57ab687.blob.core.windows.net/app/gcnde338mjgim84lmmek4fhyfcj7?sp=r&st=2024-06-11T04%3A00%3A50Z&se=2024-06-11T04%3A05%3A50Z&skoid=bd1c0ed2-cc32-4d36-a3b8-c29e989f9dda&sktid=665a3fd9-4577-4bd5-bbb7-b968aff9d1b7&skt=2024-06-11T04%3A00%3A50Z&ske=2024-06-11T04%3A05%3A50Z&sks=b&skv=2024-05-04&sv=2024-05-04&sr=b&rscd=inline%3B+filename%3D%22a._a._milne.jpeg%22%3B+filename*%3DUTF-8%27%27a._a._milne.jpeg&rsct=image%2Fjpeg&sig=cs7PTA1ZFZH37ntaTZfQWdrWuZjhyL3REZAP3aqdAKs%3D
Azure complains about the signature
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:df5ce959-601e-0017-07b3-bbf62c000000
Time:2024-06-11T04:00:50.6725539Z</Message><AuthenticationErrorDetail>Signature did not match. String to sign used was r
2024-06-11T04:00:50Z
2024-06-11T04:05:50Z
/blob/app718c0c02f57ab687/app/gcnde338mjgim84lmmek4fhyfcj7
bd1c0ed2-cc32-4d36-a3b8-c29e989f9dda
665a3fd9-4577-4bd5-bbb7-b968aff9d1b7
2024-06-11T04:00:50Z
2024-06-11T04:05:50Z
b
2024-05-04





2024-05-04
b



inline; filename="a._a._milne.jpeg"; filename*=UTF-8''a._a._milne.jpeg


image/jpeg</AuthenticationErrorDetail></Error>
```

Any input would be much appreciated.

**Comment by JoeDupuis** [comment]
Thank you for working on this! Congrats on having the first PR :laughing:

A couple of notes:

When I was reading the docs on managed identities yesterday, I was still unsure of what I wanted the API to look like.

I am tempted to have the Client support both the old signature (passing the shared key to the client) and this new one where you pass the signer instead. The client could figure out which signer it needs to instantiate automatically depending on the arguments, or initialize the shared key signer by default.
Alternatively, not allowing the signer to be passed (initializing both signer just from the arguments) would mean we don't have to document the signer classes, as users would not interact with them.

Looking at the docs, I am pretty sure obtaining the token on Azure App will be slightly different (although similar). I also want to support managed ID locally for running the tests quickly (based on the docs, this looks possible), which would also be different. I would like to run the client tests for all three cases + shared key.

I might want to change a few things before merging, but I can wait so that we don't duplicate work. I won't work on this tonight, but I was thinking of looking into making the test suite run for managed id. Tell me if you start working on it before I do.

Thank you for working on this! :heart:

**Comment by dan-corneanu** [comment]
> I am tempted to have the Client support both the old signature (passing the shared key to the client) and this new one where you pass the signer instead. The client could figure out which signer it needs to instantiate automatically depending on the arguments, or initialize the shared key signer by default. Alternatively, not allowing the signer to be passed (initializing both signer just from the arguments) would mean we don't have to document the signer classes, as users would not interact with them.

Agree.
 
> Looking at the docs, I am pretty sure obtaining the token on Azure App will be slightly different (although similar). 

From what I understand it should be just a matter of reading from `localhost` and the handling of the errors seems less involved.

> I also want to support managed ID locally for running the tests quickly (based on the docs, this looks possible), which would also be different. I would like to run the client tests for all three cases + shared key.

I am not sure what you mean by `support managed ID locally`. Could you please detail this a little bit more?

> I might want to change a few things before merging, but I can wait so that we don't duplicate work. I won't work on this tonight, but I was thinking of looking into making the test suite run for managed id. Tell me if you start working on it before I do.

I am right now looking into Azurite as a possible option of running all the tests locally without the need for an actual Azure account. I'll give an update at the end of the day (NZST UTC/GMT +12 hours)

**Comment by dan-corneanu** [comment]
@JoeDupuis I've tidied up the PR and removed the signer from the blob service.
I've managed to run the existing tests with Azurite locally but only with the `shared key` option. I've encountered these issues
* didn't mange to figure out how to set up a managed identity service locally
* Azurite doesn't seem to verify the md5 against the `x-ms-blob-content-md5` header so there are 4 tests that fail because they expect the blob service to reply with an error. The rest of the tests run fine against Azurite as long as you make some minor changes to the code to accept self signed certificates and a service URIs like `<store_account>.blob.localhost:1000` or `127.0.0.1:1000`. I didn't want to pollute the PR so I haven't pushed these changes.

> ... but I was thinking of looking into making the test suite run for managed id. Tell me if you start working on it before I do.

Currently I have no idea how to move forward with testing without an Azure account. That is, to run all tests locally. So feel free to take a stab on it. I am curious to see what you have in mind.

**Comment by dan-corneanu** [comment]
> Looking at the docs, I am pretty sure obtaining the token on Azure App will be slightly different (although similar).

https://github.com/Azure/azure-sdk-for-ruby/blob/af93e66001eb56d647d9f3a10e328da8a3ec917f/runtime/ms_rest_azure/lib/ms_rest_azure/credentials/msi_token_provider.rb#L86

**Comment by dan-corneanu** [comment]
I've set up an Azure VM with Managed Identity and run all the tests with `AZURE_ACCESS_KEY` and without `AZURE_ACCESS_KEY`. All have passed.

**Comment by JoeDupuis** [comment]
> I've set up an Azure VM with Managed Identity and run all the tests with AZURE_ACCESS_KEY and without AZURE_ACCESS_KEY. All have passed.

Nice! 

> I am not sure what you mean by support managed ID locally. Could you please detail this a little bit more?

I am not sure either honestly, but I saw a couple of threads where the ability to authenticate through Entra ID locally was mentioned.

They refer to `EnvironmentCredential` from the .net SDK being able to do this by supplying these values : 

- AZURE_TENANT_ID
- AZURE_CLIENT_ID
- AZURE_CLIENT_SECRET

If the .net sdk do it, I figured there must be a way to do it.
https://www.rahulpnath.com/blog/azure-managed-service-identity-and-local-development/

That being said, it's not a huge priority, just a nice to have. Just like Azurite, I was thinking of adding support at some point. 

For now, I just want a setup that would let me run all tests for:
- Shared keys 
- A VM
- App service

Since the test suite already pass on a VM, we can merge without App service and add support in a second PR.
 
Do you want me to do a review pass? I noticed a couple typos or commented code, so I wasn't sure if you were still working on the PR.

**Comment by dan-corneanu** [comment]
> Since the test suite already pass on a VM, we can merge without App service and add support in a second PR.

Let's address this into a separate PR.

> Do you want me to do a review pass? I noticed a couple typos or commented code, so I wasn't sure if you were still working on the PR.

Let me first move the user delegation key handling into it's own `UserDelegationKeyProvider` and update the code to reuse the same key if not expired. I should have some spare time over the week-end.

**Comment by JoeDupuis** [comment]
Do you mind if I pick this up?

**Comment by dan-corneanu** [comment]
> Do you mind if I pick this up? I'll have more time to work on it this month and I am hoping to wrap up the managed identity support and start working on something else.

Ahh, I completely forgot about this. Yes, please go ahead.
Thank you.

**Comment by JoeDupuis** [comment]
I'll merge your PR to a different branch so I can add to it.

**Pull request merged**
